const BASE_DATA = [
  {id:1,name:"Helck",emoji:"🏋️",year:2023,type:"anime",genres:["action","fantasy"],imdb:7.3},
  {id:2,name:"Legend of the Galactic Heroes: Die Neue These",emoji:"🌌",year:2018,type:"anime",genres:["sci-fi","drama"],imdb:8.0},
  {id:3,name:"Cyberpunk Edgerunners",emoji:"🦾",year:2022,type:"anime",genres:["sci-fi","action","drama"],imdb:8.3},
  {id:4,name:"I Parry Everything",emoji:"🛡️",year:2023,type:"anime",genres:["fantasy","comedy"],imdb:6.8},
  {id:5,name:"Samurai Champloo",emoji:"⚔️",year:2004,type:"anime",genres:["action","adventure"],imdb:8.5},
  {id:6,name:"Neon Genesis Evangelion",emoji:"🤖",year:1995,type:"anime",genres:["sci-fi","drama","mecha"],imdb:8.5},
  {id:7,name:"Planetes",emoji:"🚀",year:2003,type:"anime",genres:["sci-fi","drama"],imdb:8.1},
  {id:8,name:"Monster",emoji:"🔪",year:2004,type:"anime",genres:["thriller","drama","mystery"],imdb:8.8},
  {id:9,name:"Gurren Lagann",emoji:"🌀",year:2007,type:"anime",genres:["action","mecha","sci-fi"],imdb:8.4},
  {id:10,name:"JoJo's Bizarre Adventure",emoji:"💪",year:2012,type:"anime",genres:["action","adventure","fantasy"],imdb:8.1},
  {id:11,name:"Mushoku Tensei",emoji:"🌿",year:2021,type:"anime",genres:["fantasy","adventure","isekai"],imdb:7.9},
  {id:12,name:"Frieren: Beyond Journey's End",emoji:"🧝",year:2023,type:"anime",genres:["fantasy","drama","adventure"],imdb:9.0},
  {id:13,name:"Dungeon Meshi",emoji:"🍲",year:2024,type:"anime",genres:["fantasy","comedy","adventure"],imdb:8.7},
  {id:14,name:"Orb: On the Movements of the Earth",emoji:"🌍",year:2024,type:"anime",genres:["historical","drama"],imdb:8.2},
  {id:15,name:"Fate/Zero",emoji:"⚗️",year:2011,type:"anime",genres:["fantasy","action","thriller"],imdb:8.3},
  {id:16,name:"Ergo Proxy",emoji:"🎭",year:2006,type:"anime",genres:["sci-fi","mystery","dystopia"],imdb:7.9},
  {id:17,name:"Black Lagoon",emoji:"🚢",year:2006,type:"anime",genres:["action","crime"],imdb:7.9},
  {id:18,name:"Golden Kamuy",emoji:"🦌",year:2018,type:"anime",genres:["historical","adventure","action"],imdb:7.9},
  {id:19,name:"Gintama",emoji:"🍭",year:2006,type:"anime",genres:["comedy","action","sci-fi"],imdb:8.9},
  {id:20,name:"Bleach",emoji:"🗡️",year:2004,type:"anime",genres:["action","fantasy","shounen"],imdb:8.2},
  {id:21,name:"Tomorrow's Joe",emoji:"🥊",year:1970,type:"anime",genres:["sport","drama"],imdb:8.3},
  {id:22,name:"Rainbow",emoji:"🌈",year:2010,type:"anime",genres:["drama","crime","historical"],imdb:8.6},
  {id:23,name:"Chi – Chikyuu no Undou ni Tsuite",emoji:"🌐",year:2023,type:"anime",genres:["historical","drama"],imdb:8.0},
  {id:24,name:"The Kingdom of Ruin",emoji:"💀",year:2023,type:"anime",genres:["action","fantasy","drama"],imdb:5.8},
  {id:25,name:"Gate",emoji:"🏯",year:2015,type:"anime",genres:["action","fantasy","military"],imdb:7.3},
  {id:26,name:"Devilman Crybaby",emoji:"😈",year:2018,type:"anime",genres:["action","horror","drama"],imdb:7.7},
  {id:27,name:"Pluto",emoji:"🤖",year:2023,type:"anime",genres:["sci-fi","mystery","drama"],imdb:8.5},
  {id:28,name:"Wolf's Rain",emoji:"🐺",year:2003,type:"anime",genres:["sci-fi","adventure","drama"],imdb:7.7},
  {id:29,name:"Banana Fish",emoji:"🍌",year:2018,type:"anime",genres:["action","crime","drama"],imdb:8.2},
  {id:30,name:"Texhnolyze",emoji:"🏚️",year:2003,type:"anime",genres:["sci-fi","dystopia","drama"],imdb:7.7},
  {id:31,name:"The Daily Life of the Immortal King",emoji:"👑",year:2020,type:"anime",genres:["fantasy","comedy","isekai"],imdb:7.5},
  {id:32,name:"My Hero Academia",emoji:"💥",year:2016,type:"anime",genres:["action","superhero","shounen"],imdb:8.0},
  {id:33,name:"Fire Force",emoji:"🔥",year:2019,type:"anime",genres:["action","fantasy","shounen"],imdb:7.7},
  {id:34,name:"To Be Hero X",emoji:"🦸",year:2024,type:"anime",genres:["action","comedy"],imdb:7.2},
  {id:35,name:"Shangri-La Frontier",emoji:"🎮",year:2023,type:"anime",genres:["fantasy","action","isekai"],imdb:7.8},
  {id:36,name:"Primal",emoji:"🦕",year:2019,type:"anime",genres:["action","adventure"],imdb:8.7},
  {id:37,name:"Apocalypse Bringer Mynoghra",emoji:"👾",year:null,type:"anime",genres:["fantasy","strategy"],imdb:null},
  {id:38,name:"Cinderella Gray",emoji:"🐎",year:2025,type:"anime",genres:["sport","drama"],imdb:null},
  {id:39,name:"My Isekai Life",emoji:"🌿",year:2022,type:"anime",genres:["fantasy","isekai","adventure"],imdb:6.5},
  {id:40,name:"Dragon Quest: The Adventure of Dai",emoji:"🐉",year:2020,type:"anime",genres:["action","fantasy","adventure"],imdb:8.1},
  {id:41,name:"Ao Ashi",emoji:"⚽",year:2022,type:"anime",genres:["sport","drama"],imdb:7.8},
  {id:42,name:"Let This Grieving Soul Retire",emoji:"😮‍💨",year:2023,type:"anime",genres:["fantasy","comedy"],imdb:7.0},
  {id:43,name:"Spy x Family",emoji:"🕵️",year:2022,type:"anime",genres:["action","comedy","family"],imdb:8.2},
  {id:101,name:"Vampire Hunter D: Bloodlust",emoji:"🧛",year:2000,type:"anime-film",genres:["action","horror","fantasy"],imdb:7.8},
  {id:102,name:"Patlabor 2: The Movie",emoji:"🤖",year:1993,type:"anime-film",genres:["mecha","sci-fi","thriller"],imdb:7.5},
  {id:103,name:"Slime Movie: Tears of the Azure Sea",emoji:"🌊",year:2022,type:"anime-film",genres:["fantasy","isekai","adventure"],imdb:6.8},
  {id:104,name:"Metal Skin Panic MADOX-01",emoji:"🦾",year:1987,type:"anime-film",genres:["mecha","action","comedy"],imdb:6.5},
  {id:105,name:"Perfect Blue",emoji:"💙",year:1997,type:"anime-film",genres:["thriller","horror","drama"],imdb:8.0},
  {id:106,name:"Redline",emoji:"🏎️",year:2009,type:"anime-film",genres:["action","sci-fi","sport"],imdb:7.5},
  {id:107,name:"Detective Conan: La Fiancée de Shibuya",emoji:"🔍",year:2022,type:"anime-film",genres:["mystery","thriller","action"],imdb:7.2},
  {id:201,name:"The Hurricane",emoji:"🥊",year:1999,type:"film",genres:["biopic","drama","sport"],imdb:7.6},
  {id:202,name:"Mystic River",emoji:"🌊",year:2003,type:"film",genres:["thriller","drama","mystery"],imdb:7.9},
  {id:203,name:"Zodiac",emoji:"🔭",year:2007,type:"film",genres:["thriller","crime","mystery"],imdb:7.7},
  {id:204,name:"Eyes Wide Shut",emoji:"👁️",year:1999,type:"film",genres:["thriller","mystery","drama"],imdb:7.5},
  {id:205,name:"Ray",emoji:"🎹",year:2004,type:"film",genres:["biopic","drama","music"],imdb:7.7},
  {id:206,name:"Capote",emoji:"✒️",year:2005,type:"film",genres:["biopic","drama","crime"],imdb:7.4},
  {id:207,name:"The Last King of Scotland",emoji:"🦁",year:2006,type:"film",genres:["biopic","thriller","drama"],imdb:7.6},
  {id:208,name:"Lincoln",emoji:"🎩",year:2012,type:"film",genres:["biopic","historical","drama"],imdb:7.3},
  {id:209,name:"Dallas Buyers Club",emoji:"💊",year:2013,type:"film",genres:["biopic","drama"],imdb:8.0},
  {id:210,name:"Wind River",emoji:"❄️",year:2017,type:"film",genres:["thriller","crime","drama"],imdb:7.7},
  {id:211,name:"Another Round",emoji:"🍺",year:2020,type:"film",genres:["drama","comedy"],imdb:7.7},
  {id:212,name:"Se7en",emoji:"🕵️",year:1995,type:"film",genres:["thriller","crime","mystery"],imdb:8.6},
  {id:213,name:"The Godfather I, II & III",emoji:"🌹",year:1972,type:"film",genres:["crime","drama"],imdb:9.2},
  {id:214,name:"Good Will Hunting",emoji:"📐",year:1997,type:"film",genres:["drama"],imdb:8.3},
  {id:215,name:"Little Miss Sunshine",emoji:"🚌",year:2006,type:"film",genres:["comedy","drama"],imdb:7.8},
  {id:216,name:"Taxi Driver",emoji:"🚖",year:1976,type:"film",genres:["thriller","crime","drama"],imdb:8.2},
  {id:217,name:"The Lighthouse",emoji:"🔦",year:2019,type:"film",genres:["horror","thriller","drama"],imdb:7.4},
  {id:218,name:"Primal Fear",emoji:"⚖️",year:1996,type:"film",genres:["thriller","crime","drama"],imdb:7.7},
  {id:219,name:"Hamnet",emoji:"📜",year:2025,type:"film",genres:["historical","drama"],imdb:null},
  {id:220,name:"Hell or High Water",emoji:"🤠",year:2016,type:"film",genres:["crime","thriller","western"],imdb:7.6},
  {id:221,name:"Parasite",emoji:"🏠",year:2019,type:"film",genres:["thriller","drama","comedy"],imdb:8.5},
  {id:222,name:"Oldboy",emoji:"🔨",year:2003,type:"film",genres:["thriller","mystery","drama"],imdb:8.4},
  {id:223,name:"Memories of Murder",emoji:"🕵️",year:2003,type:"film",genres:["crime","thriller","drama"],imdb:8.1},
  {id:224,name:"The Color of Paradise",emoji:"🌸",year:1999,type:"film",genres:["drama","family"],imdb:8.1},
  {id:225,name:"A Separation",emoji:"💔",year:2011,type:"film",genres:["drama"],imdb:8.3},
  {id:226,name:"The Fighter",emoji:"🥊",year:2010,type:"film",genres:["biopic","drama","sport"],imdb:7.8},
  {id:227,name:"The Score",emoji:"💰",year:2001,type:"film",genres:["crime","thriller"],imdb:6.9},
  {id:228,name:"Philadelphia",emoji:"⚖️",year:1993,type:"film",genres:["drama"],imdb:7.7},
  {id:229,name:"Mean Streets",emoji:"🗽",year:1973,type:"film",genres:["crime","drama"],imdb:7.2},
  {id:230,name:"Dead Poets Society",emoji:"📖",year:1989,type:"film",genres:["drama"],imdb:8.1},
  {id:231,name:"Braveheart",emoji:"🏴󠁧󠁢󠁳󠁣󠁴󠁿",year:1995,type:"film",genres:["historical","action","drama"],imdb:8.3},
  {id:232,name:"The 13th Warrior",emoji:"🪓",year:1999,type:"film",genres:["historical","action","adventure"],imdb:6.6},
  {id:233,name:"Warcraft",emoji:"🧙",year:2016,type:"film",genres:["fantasy","action","adventure"],imdb:6.8},
  {id:234,name:"Prisoners",emoji:"⛓️",year:2013,type:"film",genres:["thriller","mystery","drama"],imdb:8.1},
  {id:235,name:"A Time to Kill",emoji:"⚖️",year:1996,type:"film",genres:["thriller","drama","crime"],imdb:7.4},
  {id:236,name:"The Painted Veil",emoji:"🎨",year:2006,type:"film",genres:["romance","drama"],imdb:7.4},
  {id:237,name:"The Banker",emoji:"💵",year:2020,type:"film",genres:["biopic","drama"],imdb:6.6},
  {id:238,name:"Tucker: The Man and His Dream",emoji:"🚗",year:1988,type:"film",genres:["biopic","drama"],imdb:7.3},
  {id:239,name:"The Villagers (Dongnesaramdeul)",emoji:"🏘️",year:2022,type:"film",genres:["thriller","mystery"],imdb:7.1},
  {id:240,name:"The Gangster, the Cop, the Devil",emoji:"🔫",year:2019,type:"film",genres:["crime","action","thriller"],imdb:7.1},
  {id:241,name:"Ford v Ferrari",emoji:"🏁",year:2019,type:"film",genres:["biopic","drama","sport"],imdb:8.1},
  {id:242,name:"F1",emoji:"🏎️",year:2025,type:"film",genres:["sport","drama","action"],imdb:null},
  {id:243,name:"Rush",emoji:"🏎️",year:2013,type:"film",genres:["biopic","sport","drama"],imdb:8.1},
  {id:244,name:"Drive",emoji:"🌃",year:2011,type:"film",genres:["action","thriller","crime"],imdb:7.8},
  {id:245,name:"Ran",emoji:"⛩️",year:1985,type:"film",genres:["historical","drama","action"],imdb:8.2},
  {id:246,name:"Citizen Kane",emoji:"🎥",year:1941,type:"film",genres:["drama","mystery"],imdb:8.3},
  {id:247,name:"Silence",emoji:"🕯️",year:2016,type:"film",genres:["historical","drama"],imdb:7.1},
  {id:248,name:"The Smashing Machine",emoji:"🥊",year:2025,type:"film",genres:["biopic","sport","drama"],imdb:null},
  {id:249,name:"My Left Foot",emoji:"🦶",year:1989,type:"film",genres:["biopic","drama"],imdb:7.9},
  {id:250,name:"They Live",emoji:"👽",year:1988,type:"film",genres:["sci-fi","action","horror"],imdb:7.3},
  {id:251,name:"Planet of the Apes",emoji:"🦍",year:1968,type:"film",genres:["sci-fi","action"],imdb:8.0},
  {id:252,name:"The Battle of Algiers",emoji:"🪖",year:1966,type:"film",genres:["historical","drama","war"],imdb:8.1},
  {id:253,name:"Spotlight",emoji:"📰",year:2015,type:"film",genres:["drama","crime","mystery"],imdb:8.1},
  {id:254,name:"Deepwater Horizon",emoji:"🛢️",year:2016,type:"film",genres:["thriller","drama","action"],imdb:7.1},
  {id:255,name:"Bad Boys: Ride or Die",emoji:"💥",year:2024,type:"film",genres:["action","comedy","crime"],imdb:6.2},
  {id:256,name:"Something the Lord Made",emoji:"❤️‍🩹",year:2004,type:"film",genres:["biopic","drama"],imdb:7.7},
  {id:257,name:"Demolition",emoji:"🔨",year:2015,type:"film",genres:["drama"],imdb:6.9},
  {id:258,name:"Brothers",emoji:"🎖️",year:2009,type:"film",genres:["drama","war"],imdb:7.1},
  {id:259,name:"The Machinist",emoji:"🏭",year:2004,type:"film",genres:["thriller","mystery","drama"],imdb:7.7},
  {id:260,name:"Incendies",emoji:"🔥",year:2010,type:"film",genres:["drama","mystery","war"],imdb:8.2},
  {id:261,name:"Kids",emoji:"🛹",year:1995,type:"film",genres:["drama"],imdb:7.4},
  {id:262,name:"Hero (Zhang Yimou)",emoji:"🏹",year:2002,type:"film",genres:["action","historical","martial arts"],imdb:7.9},
  {id:263,name:"Meet Joe Black",emoji:"💀",year:1998,type:"film",genres:["romance","drama","fantasy"],imdb:7.2},
  {id:264,name:"King Arthur",emoji:"⚔️",year:2004,type:"film",genres:["historical","action","adventure"],imdb:6.3},
  {id:265,name:"Virgin Territory",emoji:"🏰",year:2007,type:"film",genres:["comedy","adventure","romance"],imdb:5.4},
  {id:266,name:"Jujutsu Kaisen 0",emoji:"🌸",year:2021,type:"film",genres:["action","fantasy","horror"],imdb:7.6},
  {id:301,name:"Mindhunter",emoji:"🧠",year:2017,type:"serie",genres:["thriller","crime","drama"],imdb:8.6},
  {id:302,name:"Fargo",emoji:"❄️",year:2014,type:"serie",genres:["crime","thriller","comedy"],imdb:8.9},
  {id:303,name:"Ozark",emoji:"💵",year:2017,type:"serie",genres:["crime","thriller","drama"],imdb:8.4},
  {id:304,name:"The Sopranos",emoji:"🍝",year:1999,type:"serie",genres:["crime","drama"],imdb:9.2},
  {id:305,name:"Mad Men",emoji:"🥃",year:2007,type:"serie",genres:["drama"],imdb:8.6},
  {id:306,name:"Succession",emoji:"🏢",year:2018,type:"serie",genres:["drama","comedy"],imdb:8.9},
  {id:307,name:"House of Cards",emoji:"🃏",year:2013,type:"serie",genres:["thriller","drama","politics"],imdb:8.7},
  {id:308,name:"Twin Peaks",emoji:"☕",year:1990,type:"serie",genres:["mystery","thriller","drama"],imdb:8.8},
  {id:309,name:"Lost",emoji:"🏝️",year:2004,type:"serie",genres:["mystery","drama","sci-fi"],imdb:8.3},
  {id:310,name:"Prison Break",emoji:"🔓",year:2005,type:"serie",genres:["thriller","crime","action"],imdb:8.3},
  {id:311,name:"Severance",emoji:"🪪",year:2022,type:"serie",genres:["sci-fi","thriller","mystery"],imdb:8.7},
  {id:312,name:"Westworld",emoji:"🤠",year:2016,type:"serie",genres:["sci-fi","thriller","western"],imdb:8.6},
  {id:313,name:"Six Feet Under",emoji:"⚰️",year:2001,type:"serie",genres:["drama","comedy"],imdb:8.7},
  {id:314,name:"The Leftovers",emoji:"🕊️",year:2014,type:"serie",genres:["drama","mystery","sci-fi"],imdb:8.3},
  {id:315,name:"Person of Interest",emoji:"📷",year:2011,type:"serie",genres:["sci-fi","thriller","action"],imdb:8.4},
  {id:316,name:"Outlander",emoji:"🏴󠁧󠁢󠁳󠁣󠁴󠁿",year:2014,type:"serie",genres:["historical","romance","drama","fantasy"],imdb:8.4},
  {id:317,name:"Dexter",emoji:"🔪",year:2006,type:"serie",genres:["thriller","crime","drama"],imdb:8.6},
  {id:318,name:"Band of Brothers",emoji:"🎖️",year:2001,type:"serie",genres:["war","drama","historical"],imdb:9.4},
  {id:319,name:"The Penguin",emoji:"🐧",year:2024,type:"serie",genres:["crime","action","drama"],imdb:8.5},
  {id:320,name:"A Knight of the Seven Kingdoms",emoji:"⚔️",year:2024,type:"serie",genres:["fantasy","historical","drama"],imdb:7.8},
  {id:321,name:"Invincible",emoji:"🦸",year:2021,type:"serie",genres:["action","superhero","drama"],imdb:8.7},
  {id:322,name:"Black Sails",emoji:"☠️",year:2014,type:"serie",genres:["adventure","action","historical"],imdb:8.2},
  {id:323,name:"The Boys",emoji:"💥",year:2019,type:"serie",genres:["action","superhero","comedy","drama"],imdb:8.7},
  {id:324,name:"Godfather of Harlem",emoji:"🎷",year:2019,type:"serie",genres:["crime","drama","historical"],imdb:8.2},
  {id:401,name:"Vinland Saga",emoji:"⚔️",year:2005,type:"manga",genres:["historical","action","adventure"],imdb:null},
  {id:402,name:"Berserk",emoji:"🗡️",year:1989,type:"manga",genres:["dark fantasy","action","horror"],imdb:null},
  {id:403,name:"Homunculus",emoji:"🧠",year:2003,type:"manga",genres:["mystery","psychological","horror"],imdb:null},
  {id:404,name:"The Climber",emoji:"🧗",year:1994,type:"manga",genres:["sport","drama","adventure"],imdb:null},
  {id:405,name:"20th Century Boys",emoji:"🤖",year:1999,type:"manga",genres:["mystery","sci-fi","thriller"],imdb:null},
  {id:406,name:"Usogui",emoji:"🎲",year:2006,type:"manga",genres:["thriller","strategy","action"],imdb:null},
  {id:407,name:"Gon",emoji:"🦕",year:1991,type:"manga",genres:["adventure","action"],imdb:null},
  {id:408,name:"Slam Dunk",emoji:"🏀",year:1990,type:"manga",genres:["sport","comedy","drama"],imdb:null},
  {id:409,name:"Steel Ball Run (JoJo Part 7)",emoji:"🐎",year:2004,type:"manga",genres:["action","adventure","fantasy"],imdb:null},
  {id:410,name:"Yotsuba&!",emoji:"🌻",year:2003,type:"manga",genres:["comedy","slice of life"],imdb:null},
  {id:411,name:"Oyasumi Punpun",emoji:"🕊️",year:2007,type:"manga",genres:["drama","psychological","slice of life"],imdb:null},
  {id:412,name:"A Bride's Story",emoji:"🧵",year:2008,type:"manga",genres:["historical","romance","drama"],imdb:null},
  {id:413,name:"Veil",emoji:"🌫️",year:null,type:"manga",genres:["mystery","thriller"],imdb:null},
  {id:414,name:"Real",emoji:"🏀",year:1999,type:"manga",genres:["sport","drama"],imdb:null},
  {id:415,name:"JoJo's Bizarre Adventure",emoji:"💪",year:1987,type:"manga",genres:["action","adventure","fantasy"],imdb:null},
  {id:416,name:"Grand Blue",emoji:"🤿",year:2014,type:"manga",genres:["comedy","slice of life"],imdb:null}
];